### ISSUE TITLE
PDF is corrupted

### ISSUE THREAD

**Issue by philsimon** [WordPress/book#102]
I tried to download it a bunch of times. It finishes, but I receive this error:

http://screencast.com/t/4YjqX5iAE

**Comment by wturrell** [comment]
For what it's worth [it](https://github.com/WordPress/book/blob/master/Formats/Milestones-The-Story-of-WordPress.pdf) loads fine for me on Mac OS X in Preview and Adobe Acrobat Pro (9.5.5).

**Comment by kjellr** [comment]
Thanks for the heads up. It's been working fine for me as well. Tested in:

- Adobe Acrobat Reader DC (v2015.009.20077)
- Adobe Acrobat Pro (v2015.009.20077)
- Preview.app (v8.1)

In any case, I just uploaded a new version, so @philsimon, would you mind giving this one a try? 
https://github.com/WordPress/book/tree/master/Formats

Thank you!

**Comment by philsimon** [comment]
Same issue. Mac, downloading from Chrome.

**Comment by kjellr** [comment]
Can you try visiting the file's page here: https://github.com/WordPress/book/blob/master/Formats/Milestones-The-Story-of-WordPress.pdf

![chrome](https://cloud.githubusercontent.com/assets/1202812/11722615/c2fddbf0-9f37-11e5-9060-f13057760e6b.png)

Typically, Chrome will load the PDF directly in-browser as shown above, and you should be able to download it to your computer by right-clicking the "Raw" button in the upper right. 

Let me know if that works for you!

**Comment by philsimon** [comment]
It worked. Thanks.
