### ISSUE TITLE
Link anchors are too long

### ISSUE THREAD

**Issue by Rarst** [WordPress/book#104]
Finished epub version on my book reader and had bit of an issue with link anchors — they often covered whole area of screen where I tap to scroll. Paragraphs worth of a single link or consecutive links.

**Comment by kristastevens** [comment]
Hello @Rarst -- can you share a particular passage or section of the book or link that was problematic? Can you share what type of reader you're seeing this in as well as the type of device? Any specific information you can share would be helpful. Thanks!

**Comment by Rarst** [comment]
Example (Part 4 / 29):
> Justin Tadlock (<a href="https://profiles.wordpress.org/greenshady">greenshady</a>) released the Options theme to prove that there was <a href="http://justintadlock.com/archives/2008/02/24/options-wordpress-theme">nothing to stop developers from releasing a free theme fully packed with bells and whistles</a>. He was one of the first to explore an alternative business model, setting up <a href="http://justintadlock.com/archives/2008/05/31/project-m">his own theme club</a>. In contrast to theme sales, he wanted to create a community around theme releases and support. Later that year, he <a href="http://justintadlock.com/archives/2008/08/05/wordpress-theme-club-launch">launched Theme Hybrid</a>.

My device is Pocket Book 630 (with large font since my eyesight is crap).

**Comment by hlashbrooke** [comment]
I have the same issue on my Kindle - frequently when I tap to turn the page I end up clicking on a link, which then opens the browser. With wifi off it gives me an error that I have to click out of and then hit the back button to get back to reading. This would be possible even if the link anchors were short, but with the long anchors like we have, it makes it all to easy to do. More of an annoyance than anything else really.

**Comment by kristastevens** [comment]
I've edited the passage you note, @Rarst to reduce the size of the anchors. New versions of the book will be up in the repo this afternoon. Marking this issue closed.

**Comment by Rarst** [comment]
To be clear that was just _one_ example. It would be hard to enumerate all links quickly. :)

**Comment by kristastevens** [comment]
Understood. We'll keep link anchor length in mind as the book iterates, though we don't have any plans to go through line by line and fix them all at this time.
