### ISSUE TITLE
Explanation of terminology for 'ping' in Chapter 1

### ISSUE THREAD

**Issue by Japh** [WordPress/book#13]
I'm not sure whether you think it's necessary or not, but where you're explaining what a _permalink_ and _trackback_ are, you use the term _ping_ (also jargon in this context) without explanation.

I would think if someone didn't know what a permalink or trackback was, they also won't understand what a ping is.

**Comment by smckeown** [comment]
This might be necessary. Not sure though. @kristastevens?

**Comment by kristastevens** [comment]
Ping @mikedang who is working on Part 1.

**Comment by mikedang** [comment]
@smckeown @kristastevens I agree that it's not necessary. My sense is that this is a historical look, and not a resource guide.
