### ISSUE TITLE
Haiku Submissions

### ISSUE THREAD

**Issue by mathetos** [WordPress/book#75]
How do you want Haiku's submitted? As pull requests!? That'd be a first for me. What a great project, looking forward to the final product for sure.

**Comment by smckeown** [comment]
As pull requests please. I've added instructions to the readme. But here they are too:

1. Create a fork of the repo
2. Add your haiku to the haiku.md file (if there is already one there, add it underneath. We'll decide which ones to choose).
3. Submit a pull request.
