### ISSUE TITLE
Odd image cropping...

### ISSUE THREAD

**Issue by georgestephanis** [WordPress/book#76]
The image -- https://github.com/WordPress/book/blob/master/Resources/images/44/post-formats.jpg -- may be better off cropped just a few pixels shorter.  The side meta box currently just shows a line at the bottom of the image where the next meta box would stop, and it feels a bit awkward.

![image](https://cloud.githubusercontent.com/assets/941023/6531175/14089328-c405-11e4-9f27-bdb8255e9d6a.png)

**Comment by smckeown** [comment]
Good idea. Submit a pull request?

**Comment by DrewAPicture** [comment]
@georgestephanis Did this ever get adjusted?
