### ISSUE TITLE
BDFL examples

### ISSUE THREAD

**Issue by rmccue** [WordPress/book#80]
Hi! Trying to avoid spoiling too much of the book, but couldn't resist reading a few select chapters. :)

In `Part 3/24-habari.md`, it contains the following:

> Notable BDFLs are Linus Torvalds of Linux and Rasmus Lerdorf of PHP.

However, Rasmus doesn't actually hold the title of BDFL, as PHP's decision-making process is [consensus based](https://wiki.php.net/rfc/voting). A much better example would be Guido van Rossum of Python, for whom the term was originally created ([citation](http://en.wikipedia.org/wiki/Benevolent_dictator_for_life)).

Note that the above Wikipedia article does claim that Rasmus is the BDFL, although it sites a secondary source with no verification for the claim. Van Rossum's claim has many more documents to support it, including [an article written by him](http://www.artima.com/weblogs/viewpost.jsp?thread=235725) talking about the history of the title, and [an entry in the Jargon File](http://www.catb.org/jargon/html/B/BDFL.html).

**Comment by rmccue** [comment]
Further on van Rossum's role, this [April Fool's retirement PEP](https://www.python.org/dev/peps/pep-0401/) (Python Enhancement Proposal), which acknowledges the title and humorously retires it.

**Comment by smckeown** [comment]
Fine by me. Submit a pull request?

**Comment by smckeown** [comment]
Fixed: https://github.com/WordPress/book/commit/4741c74a1e03b3e15d610a04a3834fd46c72e33b
