### ISSUE TITLE
The use of "premium" versus "commercial" for themes.

### ISSUE THREAD

**Issue by krogsgard** [WordPress/book#85]
I'd like to propose that the book would be better served to reference paid themes as "commercial" versus "premium" wherever possible and still keep context.

I know that some chapters, like chapter 29, refers to the "premium" theme marketing element, but within that chapter where it's not discussing the "premium" moniker itself, but labeling a theme shop, and in other chapters where it's simply labeling a theme shop as premium, the book would be better to showcase the themes as commercial instead.

A couple of quick examples:

Chapter 29:
> For designers and developers making free and premium themes, what distinguished them was the time and effort they put into them, and the level of effort required to set them up. In an interview in June 2008, premium theme developer Darren Hoyt talks about the differences between creating a free and a premium theme. He outlines his considerations:

The second instance I think, at least, should say commercial, as it's descriptive of the real thing, not the practice of calling themes premium. The third makes sense as premium. The first is debatable...

Chapter 31:
> Premium theme developers and the wider community were annoyed. 

and

> As the first to embrace the GPL, Brian Gardner advised other premium theme sellers.

Both of these instances would be better served to say commercial, I believe. The middle of the chapter that explains Matt's stance on "Premium", "Proprietary", and other labels is more difficult to determine appropriate labeling.

In general, I'd love to see the book notate commercial instead of premium when describing themes that cost money. Of course, this requires balance with the common terminology that was used during that period and now, where appropriate.

I completely trust Siobhan's ability to make that balance, but would at least like to review the usage of the word "premium" throughout the book to see if it can or should be replaced with more accurate terminology.

**Comment by Otto42** [comment]
Agreed. I personally use "non-free", but commercial is acceptable too.

**Comment by smckeown** [comment]
I appreciate your position, and it's certainly one I agree with. The designation "commercial" is more appropriate than "premium" when talking about these types of for-sale themes today.

However, when writing about them there is a subtle difference. When I talk about "premium themes" I'm talking about the phenomenon of people self-designating themes as premium. So, for example chapter 29 is titled "Premium Themes" and in that case the adjective is correct as the title is referring specifically to these types of themes.

I have tried to be consistent with this but I'm sure I won't have got it right every time. 

Care to make note of the ones you think need to be changed while you're reading, and then post it here when you're done? :)

**Comment by DrewAPicture** [comment]
@krogsgard Care to follow up here?

**Comment by AlbertGuadan** [comment]
I like the idea of using "Commercial" as  the hierarchy.

**Comment by kristastevens** [comment]
Issue seems to have been abandoned. Closing.
