### ISSUE TITLE
Could there be more documentation on "project icon"?

### ISSUE THREAD

**Issue by field2** [WordPress/book#89]
See https://wordpress.org/news/2008/11/the-results-of-project-icon/
It's not mentioned in the book anywhere, but it had a big impact on the new layout of the admin, and may have been the first crowd-sourced design feature by an open source project in history.

**Comment by smckeown** [comment]
Yeah - we can fit that in for sure. It was in a previous version but must have got lost in the restructuring. I'll look at where it can be slotted back in.
