### ISSUE TITLE
Release Leads

### ISSUE THREAD

**Issue by GaryJones** [WordPress/book#98]
I can't find anywhere that lists all of the release leads for each version since WP [transitioned to release leads](https://github.com/WordPress/book/blob/master/Content/Part%206/40-transition-release-leads.md).

https://make.wordpress.org/core/tag/release-lead/

Could they be added to the relevant chapter or an appendix?

**Comment by smckeown** [comment]
Added here: https://github.com/WordPress/book/blob/master/Content/Part%206/endmatter.md

Up to 3.8. The book ends with 3.8. Later release leads can be added in a later version.
